export const dogBingoOptions = ["Abandoned Poop",
"Beagle",
"Belly up",
"Big man/tiny dog",
"Black & White",
"Black dog",
"Border Collie",
"Brown & White",
"Brown Dog",
"Bulldog",
"Butt Dragging",
"Butt Sniffing",
"Butt Sniffing Duo",
"Cat in a pram/backpack",
"Cavoodle",
"Chasing Ball",
"Chasing Frisbee",
"Chasing Stick",
"Chihuahua",
"Chihuahua Duo",
"Chocolate dog",
"Collar - Black",
"Collar - Blue",
"Collar - Diamante",
"Collar - Green",
"Collar - LED",
"Collar - Pink",
"Collar - Red",
"Collar - Spiked",
"Cone of Shame",
"Corgi",
"Dachshund",
"Dachshund Duo",
"Dalmatian",
"Digging",
"Dog with a stick",
"Dog with a toy",
"Dog/Owner lookalike",
"Duo - Any kind",
"Dyed fur",
"Ears - floppy",
"Ears - wet",
"Fighting",
"French Bulldog",
"Galloping",
"German Shepherd",
"Giant floof",
"Golden Retriever",
"Grey Dog",
"Greyhound",
"HUGE dog",
"Happy face",
"Humping",
"Husky",
"In a pram",
"Italian Greyhound",
"Jack Russell",
"King Charles Cavalier",
"Labrador",
"Maltese",
"Muzzle",
"Old Dog",
"On skateboard",
"Owner ignoring poop",
"Owner picking up poop",
"Pack (4+)",
"Patched Eye",
"Peeing",
"Peeing on a lamp post",
"Peeing on a tree",
"Pomeranian",
"Poodle",
"Pooping",
"Pug",
"Pug Duo",
"Receiving treats",
"Rottweiler",
"Samoyed",
"Scarf",
"Shiba Inu",
"Slobbery dog",
"Sniffing Pee",
"Three legged dog",
"Tiny Floof",
"Tiny aggressive dog",
"Tiny dog in a jacket",
"Trio - Any kind",
"Trotting",
"Two dogs, one stick",
"Two sniffs, one butt",
"VERY waggly tail",
"Wearing Sunglasses",
"Wet dog",
"White Dog",
"Zooming"]